/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/5 18:44:21
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class Enemy : FFramework.MVVM.View
    {
        public UnityEngine.Transform @Enemy_Transform { get; private set; } = default;
        public UnityEngine.Animator @Enemy_Animator { get; private set; } = default;


        public void InitRefs()
        {
            @Enemy_Transform = GetComponent<UnityEngine.Transform>();
            @Enemy_Animator = GetComponent<UnityEngine.Animator>();

        }

        
    }
    
}
