/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/7 23:31:44
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class Enemy : FFramework.MVVM.View
    {
        public UnityEngine.Transform @Enemy_Transform { get; private set; } = default;
        public UnityEngine.Animator @Enemy_Animator { get; private set; } = default;
        public UnityEngine.Rigidbody @Enemy_Rigidbody { get; private set; } = default;


        public void InitRefs()
        {
            @Enemy_Transform = GetComponent<UnityEngine.Transform>();
            @Enemy_Animator = GetComponent<UnityEngine.Animator>();
            @Enemy_Rigidbody = GetComponent<UnityEngine.Rigidbody>();

        }

        
    }
    
}
