/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/8 16:19:34
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class EventSystem : FFramework.MVVM.View
    {
        public UnityEngine.EventSystems.EventSystem @EventSystem_EventSystem { get; private set; } = default;


        public void InitRefs()
        {
            @EventSystem_EventSystem = GetComponent<UnityEngine.EventSystems.EventSystem>();

        }

        
    }
    
}
