/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/7 23:11:50
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class GameMainPanel : FFramework.MVVM.View
    {
        public UnityEngine.CanvasGroup @GameMainPanel_CanvasGroup { get; private set; } = default;
        public UnityEngine.UI.Text @PlanePositionText_Text { get; private set; } = default;
        public UnityEngine.UI.Text @KillCountText_Text { get; private set; } = default;


        public void InitRefs()
        {
            @GameMainPanel_CanvasGroup = GetComponent<UnityEngine.CanvasGroup>();
            @PlanePositionText_Text = transform.Find(@"PlanePositionText").GetComponent<UnityEngine.UI.Text>();
            @KillCountText_Text = transform.Find(@"KillCountText").GetComponent<UnityEngine.UI.Text>();

        }

        
    }
    
}
