/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/2/21 14:53:23
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class GamePanel : FFramework.MVVM.View
    {
        public UnityEngine.CanvasGroup @GamePanel_CanvasGroup { get; private set; } = default;
        public UnityEngine.UI.Text @PositionBar_Text { get; private set; } = default;
        public UnityEngine.UI.Image @HpValue_Image { get; private set; } = default;
        public UnityEngine.UI.Text @HpText_Text { get; private set; } = default;
        public UnityEngine.UI.Image @HungryValue_Image { get; private set; } = default;
        public UnityEngine.UI.Text @HungryText_Text { get; private set; } = default;


        public void InitRefs()
        {
            @GamePanel_CanvasGroup = GetComponent<UnityEngine.CanvasGroup>();
            @PositionBar_Text = transform.Find(@"PositionBar").GetComponent<UnityEngine.UI.Text>();
            @HpValue_Image = transform.Find(@"LeftTop/HpBar/HpValue").GetComponent<UnityEngine.UI.Image>();
            @HpText_Text = transform.Find(@"LeftTop/HpBar/HpText").GetComponent<UnityEngine.UI.Text>();
            @HungryValue_Image = transform.Find(@"LeftTop/HungryBar/HungryValue").GetComponent<UnityEngine.UI.Image>();
            @HungryText_Text = transform.Find(@"LeftTop/HungryBar/HungryText").GetComponent<UnityEngine.UI.Text>();

        }

        
    }
    
}
