/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/8 23:12:07
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class GameOverPanel : FFramework.MVVM.View
    {
        public UnityEngine.RectTransform @GameOverPanel_RectTransform { get; private set; } = default;
        public UnityEngine.UI.Button @ReturnButton_Button { get; private set; } = default;


        public void InitRefs()
        {
            @GameOverPanel_RectTransform = GetComponent<UnityEngine.RectTransform>();
            @ReturnButton_Button = transform.Find(@"Panel/ReturnButton").GetComponent<UnityEngine.UI.Button>();

        }

        
    }
    
}
