/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/2/1 13:21:35
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVC;

namespace FFramework.MVC.RefCache
{
    public class GraveZone : FFramework.MVVM.View
    {


        public void InitRefs()
        {

        }

        
        private void Awake()
        {
            InitRefs();
        }

    }
    
}
