/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/2/16 15:11:37
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class MainMenuPanel : FFramework.MVVM.View
    {
        public UnityEngine.RectTransform @MainMenuPanel_RectTransform { get; private set; } = default;
        public UnityEngine.RectTransform @TransButton1_RectTransform { get; private set; } = default;
        public UnityEngine.RectTransform @TransButton2_RectTransform { get; private set; } = default;
        public UnityEngine.RectTransform @TransButton3_RectTransform { get; private set; } = default;


        public void InitRefs()
        {
            @MainMenuPanel_RectTransform = GetComponent<UnityEngine.RectTransform>();
            @TransButton1_RectTransform = transform.Find(@"TransButton1").GetComponent<UnityEngine.RectTransform>();
            @TransButton2_RectTransform = transform.Find(@"TransButton2").GetComponent<UnityEngine.RectTransform>();
            @TransButton3_RectTransform = transform.Find(@"TransButton3").GetComponent<UnityEngine.RectTransform>();

        }

        
    }
    
}
