/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/1/27 21:20:52
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVC;

namespace FFramework.MVC.RefCache
{
    public class MainMenuPanel : FFramework.MVVM.View
    {
        public UnityEngine.CanvasGroup @MainMenuPanel_CanvasGroup { get; private set; } = default;
        public UnityEngine.UI.Button @TransButton1_Button { get; private set; } = default;
        public UnityEngine.UI.Button @TransButton2_Button { get; private set; } = default;
        public UnityEngine.UI.Button @TransButton3_Button { get; private set; } = default;


        public void InitRefs()
        {
            @MainMenuPanel_CanvasGroup = GetComponent<UnityEngine.CanvasGroup>();
            @TransButton1_Button = transform.Find(@"TransButton1").GetComponent<UnityEngine.UI.Button>();
            @TransButton2_Button = transform.Find(@"TransButton2").GetComponent<UnityEngine.UI.Button>();
            @TransButton3_Button = transform.Find(@"TransButton3").GetComponent<UnityEngine.UI.Button>();

        }

        
    }
    
}
