/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/2/16 15:11:37
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class Map : FFramework.MVVM.View
    {
        public UnityEngine.Transform @Map_Transform { get; private set; } = default;


        public void InitRefs()
        {
            @Map_Transform = GetComponent<UnityEngine.Transform>();

        }

        
    }
    
}
