/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/7 23:22:32
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class MenuPanel : FFramework.MVVM.View
    {
        public UnityEngine.CanvasGroup @MenuPanel_CanvasGroup { get; private set; } = default;
        public UnityEngine.UI.Button @StartGame_Button { get; private set; } = default;
        public UnityEngine.UI.Text @MaxKillCountText_Text { get; private set; } = default;


        public void InitRefs()
        {
            @MenuPanel_CanvasGroup = GetComponent<UnityEngine.CanvasGroup>();
            @StartGame_Button = transform.Find(@"StartGame").GetComponent<UnityEngine.UI.Button>();
            @MaxKillCountText_Text = transform.Find(@"MaxKillCountText").GetComponent<UnityEngine.UI.Text>();

        }

        
    }
    
}
