/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/5 18:44:21
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class Missile : FFramework.MVVM.View
    {
        public UnityEngine.Transform @Missile_Transform { get; private set; } = default;


        public void InitRefs()
        {
            @Missile_Transform = GetComponent<UnityEngine.Transform>();

        }

        
    }
    
}
