/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/8 18:48:55
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class Missile : FFramework.MVVM.View
    {
        public UnityEngine.Rigidbody @Missile_Rigidbody { get; private set; } = default;


        public void InitRefs()
        {
            @Missile_Rigidbody = GetComponent<UnityEngine.Rigidbody>();

        }

        
    }
    
}
