/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/7 22:55:39
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class Plane : FFramework.MVVM.View
    {
        public UnityEngine.Animator @Plane_Animator { get; private set; } = default;
        public UnityEngine.Transform @Plane_Transform { get; private set; } = default;
        public FFramework.MVVM.BindableProperty<UnityEngine.Vector3> @Plane_Transform_position {get;set;}=default;
        public UnityEngine.Rigidbody @Plane_Rigidbody { get; private set; } = default;


        public void InitRefs()
        {
            @Plane_Animator = GetComponent<UnityEngine.Animator>();
            @Plane_Transform = GetComponent<UnityEngine.Transform>();
            @Plane_Transform_position = new FFramework.MVVM.BindableProperty<UnityEngine.Vector3>(@Plane_Transform,(y)=>((UnityEngine.Transform)y).position,(y,x)=>((UnityEngine.Transform)y).position=x);
            @Plane_Rigidbody = GetComponent<UnityEngine.Rigidbody>();

        }

        
    }
    
}
