/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/2/16 15:11:37
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class Player : FFramework.MVVM.View
    {
        public UnityEngine.Transform @Player_Transform { get; private set; } = default;
        public UnityEngine.Rigidbody @Player_Rigidbody { get; private set; } = default;
        public UnityEngine.Transform @Character_Transform { get; private set; } = default;
        public UnityEngine.Camera @Camera_Camera { get; private set; } = default;
        public UnityEngine.Transform @Head_Transform { get; private set; } = default;


        public void InitRefs()
        {
            @Player_Transform = GetComponent<UnityEngine.Transform>();
            @Player_Rigidbody = GetComponent<UnityEngine.Rigidbody>();
            @Character_Transform = transform.Find(@"Character").GetComponent<UnityEngine.Transform>();
            @Camera_Camera = transform.Find(@"Camera").GetComponent<UnityEngine.Camera>();
            @Head_Transform = transform.Find(@"Character/Rig1/Spine1/Spine2/Head").GetComponent<UnityEngine.Transform>();

        }

        
    }
    
}
