/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/8 16:14:58
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class Sun : FFramework.MVVM.View
    {
        public UnityEngine.Light @Sun_Light { get; private set; } = default;


        public void InitRefs()
        {
            @Sun_Light = GetComponent<UnityEngine.Light>();

        }

        
    }
    
}
