/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/2/11 16:55:57
 * UVersion : 2021.3.29f1
 *******************************************************/
using UnityEngine;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class Sun : FFramework.MVVM.View
    {
        public UnityEngine.Transform @Sun_Transform { get; private set; } = default;


        public void InitRefs()
        {
            @Sun_Transform = GetComponent<UnityEngine.Transform>();

        }

        
    }
    
}
