
/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/6 8:36:54
 * UVersion : 2021.3.29f1
 *******************************************************/
using FFramework;
using FFramework.MVVM;
using UnityEngine;

namespace FFramework.MVVM.RefCache
{
    public class FollowCameraVM : FFramework.MVVM.ViewModel<FFramework.MVVM.RefCache.FollowCamera>,IUpdate
    {
        //Select Text And Press Ctrl + K + U to uncomment.

        public override async FTask OnLoad()
        {
            TView.InitRefs();
            await FTask.CompletedTask;
        }

        public override async FTask OnUnload()
        {
            await FTask.CompletedTask;
        }

        bool syncStart = false;
        Vector3 offset;

        float syncSpeed;

        Transform target;
        public void SetFollow(Transform target,Vector3 offset,float syncSpeed=0.1f)
        {
 
            this.offset = offset;
         
            this.syncSpeed = syncSpeed;
            this.target = target;
            syncStart = true;
        }

        void IUpdate.Update(float deltaTime)
        {
            if (!syncStart) return;
            //偏移值
            Vector3 delta = TView.FollowCamera_Transform.position- this.offset - target.position;

            TView.FollowCamera_Transform.position = Vector3.Lerp(TView.transform.position,
                target.transform.position + offset, syncSpeed);
        }
    }
}

