
/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/2/16 15:11:37
 * UVersion : 2021.3.29f1
 *******************************************************/
using FFramework;
using FFramework.MVVM;
using System;
using UnityEngine;

namespace FFramework.MVVM.RefCache
{
    public class GamePanelVM : UIPanel<FFramework.MVVM.RefCache.GamePanel>
    {

        public override async FTask OnLoad()
        {
            TView.InitRefs();
            //同步生命变化
            MV.GetModel<PlayerModel>().Hp.OnPropertyChanged += Hp_OnPropertyChanged;
            MV.GetModel<PlayerModel>().MaxHp.OnPropertyChanged += Hp_OnPropertyChanged;

            //同步饥饿度变化
            MV.GetModel<PlayerModel>().Hungry.OnPropertyChanged += Hungry_OnPropertyChanged;
            MV.GetModel<PlayerModel>().MaxHungry.OnPropertyChanged += Hungry_OnPropertyChanged;

            //同步位置变化
            MV.GetModel<PlayerModel>().Position.OnPropertyChanged += Position_OnPropertyChanged;

            await FTask.CompletedTask;
        }
        private void Position_OnPropertyChanged(Vector3Int oldValue,Vector3Int newValue)
        {
            TView.PositionBar_Text.text = $"({newValue.x},{newValue.y},{newValue.z})";
        }

        private void Hp_OnPropertyChanged(float oldValue, float newValue)
        {
            TView.HpText_Text.text = $"{(int)Math.Ceiling( newValue)}/{(int)Math.Ceiling(MV.GetModel<PlayerModel>().MaxHp.Value)}";
            TView.HpValue_Image.fillAmount = (float)newValue / MV.GetModel<PlayerModel>().MaxHp.Value;
        }

        private void Hungry_OnPropertyChanged(float oldValue, float newValue)
        {
            TView.HungryText_Text.text = $"{(int)Math.Ceiling(newValue)}/{(int)Math.Ceiling(MV.GetModel<PlayerModel>().MaxHungry.Value)}";
            TView.HungryValue_Image.fillAmount = (float)newValue / MV.GetModel<PlayerModel>().MaxHungry.Value;
        }

        public override async FTask OnUnload()
        {
            await FTask.CompletedTask;
        }


    }
}

