
/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/8 23:12:07
 * UVersion : 2021.3.29f1
 *******************************************************/
using FFramework;
using FFramework.MVVM;
using UnityEngine;

namespace FFramework.MVVM.RefCache
{
    public class GameOverPanelVM : FFramework.MVVM.UIPanel<FFramework.MVVM.RefCache.GameOverPanel>
    {
        //Select Text And Press Ctrl + K + U to uncomment.

        public override async FTask OnLoad()
        {
            TView.InitRefs();
            //切换主界面
            TView.ReturnButton_Button.onClick.AddListener(() =>
            {
                Game.GameCon.SwitchMenu();
            });
            await FTask.CompletedTask;
        }

        public override async FTask OnUnload()
        {
            await FTask.CompletedTask;
        }

        public override FTask OnShow()
        {
            //可以使用CanvasGroup代替，性能更好，还能防止重排
            TView.gameObject.SetActive(true);
            Time.timeScale = 0;
            return base.OnShow();
        }

        public override FTask OnHide()
        {
            TView.gameObject.SetActive(false);
            Time.timeScale = 1;
            return base.OnHide();
        }
    }
}

