
/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/2/7 14:06:49
 * UVersion : 2021.3.29f1
 *******************************************************/
namespace FFramework.MVC.RefCache
{
    public class MapVM : FFramework.MVVM.ViewModel<FFramework.MVC.RefCache.Map>
    {
        //Select Text And Press Ctrl + K + U to uncomment.

        //public override void OnLoad()
        //{
            //await FTask.CompletedTask;
        //}

        //public override void OnUnload()
        //{
            //await FTask.CompletedTask;
        //}
    }
}

