
/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/2/11 16:48:59
 * UVersion : 2021.3.29f1
 *******************************************************/
using FFramework;
using FFramework.MVVM;
using FFramework.RefCache;
using UnityEngine;
using YooAsset;

namespace FFramework.MVVM.RefCache
{
    public class MapVM : FFramework.MVVM.ViewModel<FFramework.MVVM.RefCache.Map>
    {
 
      
        public override async FTask OnLoad()
        {
            TView.InitRefs();
            await FTask.CompletedTask;
        }

        public override async FTask OnUnload()
        {
            await FTask.CompletedTask;
        }
    }
}

