
/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/7 23:22:32
 * UVersion : 2021.3.29f1
 *******************************************************/
using FFramework;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class MenuPanelVM : FFramework.MVVM.UIPanel<FFramework.MVVM.RefCache.MenuPanel>
    {
        //Select Text And Press Ctrl + K + U to uncomment.

        public override async FTask OnLoad()
        {
            TView.InitRefs();
            TView.StartGame_Button.onClick.AddListener( Game.GameCon.SwitchGame);
            await FTask.CompletedTask;
        }

        public override async FTask OnUnload()
        {
            await FTask.CompletedTask;
        }

        public override FTask OnShow()
        {
            TView.gameObject.SetActive(true);
            var model = MV.GetModel<PlaneModel>();
            TView.MaxKillCountText_Text.text = $"最大击杀: {model.maxKillCount.Value}";
            return base.OnShow();
        }

        public override FTask OnHide()
        {
            TView.gameObject.SetActive(false);
            return base.OnHide();
        }


    }
}

