
/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/5 18:44:22
 * UVersion : 2021.3.29f1
 *******************************************************/
using FFramework;
using FFramework.MVVM;
using FFramework.RefCache;
using UnityEngine;

namespace FFramework.MVVM.RefCache
{
    public class PlaneVM : FFramework.MVVM.ViewModel<FFramework.MVVM.RefCache.Plane>,IUpdate
    {

        public override async FTask OnLoad()
        {
            TView.InitRefs();
            this.EnableUpdate();
            await FTask.CompletedTask;
        }

     


        public override async FTask OnUnload()
        {
            this.DisableUpdate();
            await FTask.CompletedTask;
        }

        void IUpdate.Update(float deltaTime)
        {
            //取得玩家操作
            float h = Input.GetAxis("Horizontal");
            float v = Input.GetAxis("Vertical");

            //读取常量Model
            var gameCfg = MV.GetModel<GameCfgModel>().Data[0];

            //移动
            TView.Plane_Rigidbody.MovePosition(gameCfg.planeMoveSpeed * Time.deltaTime * v * TView.transform.forward );
            //旋转
            TView.Plane_Rigidbody.MoveRotation(Quaternion.Euler(0, TView.Plane_Rigidbody.rotation.eulerAngles.y + h * Time.deltaTime*gameCfg.rotSpeed,0));

            

        }
    }
}

