
/*******************************************************
 * Code Generated By FFramework
 * DateTime : 2024/3/8 15:08:31
 * UVersion : 2021.3.29f1
 *******************************************************/
using FFramework;
using FFramework.MVVM;

namespace FFramework.MVVM.RefCache
{
    public class SunVM : FFramework.MVVM.ViewModel<FFramework.MVVM.RefCache.Sun>
    {
        //Select Text And Press Ctrl + K + U to uncomment.

        //public override async FTask OnLoad()
        //{
            //await FTask.CompletedTask;
        //}

        //public override async FTask OnUnload()
        //{
            //await FTask.CompletedTask;
        //}
    }
}

